name: WorkflowCall Different_Env

on: 
  workflow_call:

    inputs:
      environment:
        description: 'Name of the environment'
        required: true
        default: 'dev'
        type: string
    
    secrets:
      ENV_USERNAME:
        description: 'Username'
        required: false
      ENV_PASS:
        description: 'Password'
        required: false

jobs:

  Print_Job:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ENV_USERNAME: ${{ secrets.ENV_USERNAME }}
      ENV_PASS: ${{ secrets.ENV_PASS }}

    steps:
      - name: Checks-out
        uses: actions/checkout@v3

      - name: Print Details
        run: |
          echo "I am running in $environment environment"
          echo "User Name: $ENV_USERNAME Pass: $ENV_PASS"

      - name: Dump Password
        run: |
          echo Password is $PASSWORD
          if [[ $PASSWORD == *"PROD"* ]]; then
            echo "This is the PROD password!"
          else
            echo "This is NOT the PROD password!"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}          