name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - Arun
        - cschleiden
        required: false
      message:
        description: A formal string
        type: string
        required: true
      use-emoji:
        required: false
        type: boolean
        description: Include 🎉🤣 emojis
      environment:
        type: environment
        required: false
        description: Just an environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
